### ISSUE TITLE
Corregir botón de form a type=submit en vez de type=button

### ISSUE THREAD

**Issue by Dizkm8** [BastiancitosJr/aquachile-web#20]
Mejora la accesibilidad de la aplicación.

![Image](https://github.com/BastiancitosJr/aquachile-web/assets/105648597/131c2a55-85a8-4e35-a00d-e9809bbbfb02)

**Comment by GuillermoFA** [comment]
![Image](https://github.com/BastiancitosJr/aquachile-web/assets/131501516/a3163ca0-7fcf-480f-9930-90d1f9def391)
