### ISSUE TITLE
Corregir errores del login sobre HTML y semántica

### ISSUE THREAD

**Issue by Dizkm8** [BastiancitosJr/aquachile-web#21]
Sale esto al inspeccionar elemento

![Image](https://github.com/BastiancitosJr/aquachile-web/assets/105648597/20f04504-c531-43eb-9f48-ed334cd538e6)

**Comment by GuillermoFA** [comment]
![image](https://github.com/BastiancitosJr/aquachile-web/assets/131501516/4a230cac-468f-4b94-ae29-4fc59c2e0e02)
