### ISSUE TITLE
Proteger rutas

### ISSUE THREAD

**Issue by Dizkm8** [BastiancitosJr/aquachile-web#23]
SE puede ingresar a rutas autenticadas sin necesidad de estar autenticado

https://aquachile-front.web.app/user

**Comment by GuillermoFA** [comment]
Se utiliza authGuard mediante el token para proteger las rutas 
![image](https://github.com/BastiancitosJr/aquachile-web/assets/131501516/63a5d223-eb49-4abb-8507-0f14d8425b81) 
![image](https://github.com/BastiancitosJr/aquachile-web/assets/131501516/0cefbec5-22d8-4be5-b8b8-edf8774e9bf7)
